### ISSUE TITLE
How to remove numbers that preceed Bookmark titles?

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-mpdf#1]
Numbers are display before the titles as illustrated:
![pdf](https://cloud.githubusercontent.com/assets/360534/12351710/08fd3114-bb80-11e5-8eb2-70245b8ad27f.png)
How can I stop mPDF from generating numbers?
 Is there a way to render site specific output?

**Comment by bdolor** [comment]
The screenshot looks like a view of how the desktop application 'Preview' represents the table of contents/bookmarks of a PDF — in which case it would be something that we can't support. 

The line of code that places a number in front of the title, as well as the reason why is documented here: https://github.com/pressbooks/pressbooks/blob/dev/includes/modules/export/mpdf/class-pb-pdf.php#L499

**Comment by sswettenham** [comment]
Thanks
Yes this is a Preview Screenshot (but Adobe Acrobat Reader is the same display).
Your URL ref points to
/**
	 * Return the PDF bookmark entry for this page
	 * should be unique, using static variable for cheap cache
	 * 
	 * @staticvar int $id - to avoid collisions with identical page titles
	 * @param array $page
	 * @return string
	 */
	function getBookmarkEntry( $page ) {
		static $id = 1;
		$entry = $id . $page['post_title'];
		$id++;
		return $entry;
	}

Based on your comment I am assuming that during or a after the PDF is rendered, there is no way to automatically remove the alphanumeric in front of the titles.  The only work around appears to be to open a PDF editor and fix, then drop back file in FTP.  Not an ideal situation but I seem to recall this numbering is all due to HTML rather than XML translation?
