### ISSUE TITLE
mPDF support for fonts, global theme options

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-mpdf#15]
requires support for chapter numbers, two level TOC and custom fonts. 

depends on https://github.com/BCcampus/pressbooks-mpdf/issues/13

**Comment by bdolor** [comment]
taken care of in https://github.com/BCcampus/pressbooks-mpdf/issues/36 (duplicate)

**Comment by lucwrite** [comment]
Validated -- accepts global options. Need to do further testing with two level toc and using different themes

**Comment by lucwrite** [comment]
Also fonts require further testing.
