### ISSUE TITLE
Call to htmLawed results in errors in recent Pressbooks

### ISSUE THREAD

**Issue by crism** [BCcampus/pressbooks-mpdf#20]
Running Pressbooks 3.9.8 (dev code as of 23 March), the version of `htmLawed` available is the one loaded by:
```php
if ( file_exists( PB_PLUGIN_DIR . 'symbionts/htmLawed/htmLawed.php' ) ) {
        require_once( PB_PLUGIN_DIR . 'symbionts/htmLawed/htmLawed.php' );
}
```
The later call to `\htmlawed::filter()` then fails; the current version of `htmLawed` expects to be called just as `htmLawed()`. I’m not submitting a pull request because I’m not sure how to test this to work flexibly with the “vanilla” version of `htmlawed` too.

**Comment by bdolor** [comment]
yes of course...makes sense to me. will see what I can do.

**Comment by crism** [comment]
Er… that said, I had the direction wrong. Pressbooks has moved _from_ the `symbionts` version _to_ the `vanilla` version, so this is less urgent…

**Comment by bdolor** [comment]
excellent.
