### ISSUE TITLE
Problem while exporting to pdf

### ISSUE THREAD

**Issue by masaka222** [BCcampus/pressbooks-mpdf#22]
I get a fatal error with the version 1.6.2.1 of Pressbooks mPDF while trying to export on pdf. I'm curretly using Pressbooks Version 3.9.8.1 and Wordpress version 4.7.3.

**Fatal error:** Cannot redeclare htmLawed() (previously declared in /var/www/vhosts/.../wp-content/plugins/pressbooks/symbionts/htmLawed/htmLawed.php:12) in /var/www/vhosts/.../wp-content/plugins/pressbooks/vendor/vanilla/htmlawed/src/htmLawed/htmLawed.php on line **147**

**Comment by greatislander** [comment]
This should have been fixed in https://github.com/BCcampus/pressbooks-mpdf/pull/21, but I don't think there has been a release including that change.

**Comment by bdolor** [comment]
Thank you for reporting this error @masaka222 and thank you @greatislander for resolving it. Will be releasing an update shortly.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-mpdf/releases/tag/1.6.2.2 and new release on `wordpress.org`
