### ISSUE TITLE
folder of fonts

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#31]
Now we have two folders with fonts. The one of Pressbooks and another in Pressbooks mPDF.

90mb in Pressbooks mPDF
40mb in Pressbooks

As the fonts are not the same. Is necesary to have that duplicity? is not possible to load the fonts in Pressbooks mPDF from Pressbooks in order to have the same syle in web and in pdf? or just to have the same fonts in both folders for a better compatibility?

Are the fonts on Pressbooks selected for a specifical reason? a deep review of the fonts is necesary?

thanks

**Comment by bdolor** [comment]
@colomet thank you for reporting this — we have a sprint dedicated to mPDF issues in December. I would like to look at this as well as other issues.

**Comment by bdolor** [comment]
@colomet with [v3.0.0](https://github.com/BCcampus/pressbooks-mpdf/releases/tag/3.0.0)  the fonts are now loaded from Pressbooks. We're using mPDF as a dependency so we're not given a choice on whether they include fonts in their library or not. Font files make the plugin pretty bulky, I agree, but unless it's causing problems for you, I'm going to mark this as closed. Please re-open if there's something I can do.

**Comment by colomet** [comment]
https://github.com/mpdf/mpdf/issues/552

in version 8, mpdf would have a lite version, better for us.
