### ISSUE TITLE
Theme Parity 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-mpdf#36]
### Description 

The output of the PDF doesn't reflect the style choices defined by the theme.

**Expected behaviour** 

There's a reasonable expectation that the output format would retain/reflect all or most of the styles determined by the chosen theme. 

**Actual behaviour** 

It resembles theme independence. There is very little (any?) relationship between a web theme and the look and feel of the PDF file

**Comment by bdolor** [comment]
@lucwrite - ready for validation. There are a few known issues that I'll pick away at, like the blank pages left after the table of contents, but it would be helpful at this point to have someone else besides myself spot areas for improvement

**Comment by lucwrite** [comment]
Perfect ! I will take a look now.

**Comment by lucwrite** [comment]
Should the Global Options work now as part of this task?

**Comment by bdolor** [comment]
Global Options are covered in https://github.com/BCcampus/pressbooks-mpdf/issues/33

**Comment by lucwrite** [comment]
Brad not sure how much detail you need for this validation. Here is a link to the doc that I have been using for testing for more details [https://docs.google.com/spreadsheets/d/1HVoXlhaaVJZEcD1Kczr1GD06v6ShVww37vmeuCPebOA/edit?usp=sharing](url) Here are some high-level details: 

Parity with Prince
Title and ToC
1. Title now same
2. _ToC appears with multiple periods, styling and formatting issues_
Headings and Font_
1. Font (Serif body font) 
2. Heading size and justification and style (Note H1 has additional spacing)

Links 
1. Link parity 
2. No longer yellow box pop up for rollover

Image
1_. Captions now appear small and under image b not center justified_

Other Style
1. _Multiple blank pages_
2. Custom Infoboxes, learning objectives, exercises now look the same as Prince
3. Block quotes same as Prince
4. __Multiple blank pages in mPDF_ 
5. _No running header in mPDF_
6.

**Comment by bdolor** [comment]
multiple blank page problem resolved via https://github.com/BCcampus/pressbooks-mpdf/commit/0f8a3227e23ff4a0a771a64f77d6626de547bcc3 

toc styling is more in line with the chosen theme now

**Comment by lucwrite** [comment]
Validated: Multiple pages resolved. The toc styling still has styling issues, no longer all blue but includes multiple ...... and empty subject lines.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-mpdf/pull/44 and subsequent commits
