### ISSUE TITLE
update PB instance 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-mpdf#38]
### Description 

update our dev and production instance of PB to all the latest.

**Comment by greatislander** [comment]
@bdolor Note: the dev branch is in rapid flux as we work towards Pressbooks 5. I'd suggest sticking with master until early January. Will be blogging about the forthcoming changes before the holidays.

**Comment by bdolor** [comment]
thank you @greatislander - duly noted.

**Comment by lucwrite** [comment]
Let me know when this are on prod and I can test against and move column to done

**Comment by bdolor** [comment]
@lucwrite - production is now up to date

**Comment by lucwrite** [comment]
Validated pressbooks.bccampus.ca  and https://opentextbc.ca. All looks good. I am adding an issue to the Common Cartridge repo. With the new language Other Formats rather than Exotic formats, I think we should add (beta) to the Common Catridge Export at this stage.
