### ISSUE TITLE
Feature request: superadmin settings sync across all books

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#43]
### Description 

To be able of make the settings for superadmin

**Expected behaviour** 

Some times, we need to have all the books in the same format. Like one school o publishing company with some style guides. Such situation requires to have all the boooks following the same settings.

As super admin, to be able to change the settings and sync across all books would help.

Examples of RCP for multisite: http://docs.restrictcontentpro.com/article/1584-using-restrict-content-pro-with-wordpress-multisite

**Actual behaviour** 

Each book have independent settings. We need to open book by book and to change the settings

### System Information

- Pressbooks mPDF: 2.0
- Pressbooks: 4.5
- WordPress: 4.9.1

**Comment by greatislander** [comment]
@colomet This is really an upstream (Pressbooks) feature, I think. We were talking today about the idea of having network-level default theme options (among other things) that could override Pressbooks' defaults. I would like to implement this in first half of next year in core, which would then provide a mechanism for @bdolor and others to add network configurability to their custom options.

**Comment by colomet** [comment]
Yes, in our project, we have more than 50 books on progress and we hope to have many many more and we have in all of them the same configuration. Network-level settings are important for our situation.

**Comment by bdolor** [comment]
sounds like it's okay to close this.
