### ISSUE TITLE
features request: paper size information

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#45]
### Description 

To have more information about the sizes of the papers.

**Expected behaviour** 

To have in the settings page an info buttom with the sizes of the papers. One for all or one for each (maybe as an external link).

As you did in the last 2 types of papers
![captura de pantalla 2017-12-16 a las 9 46 08](https://user-images.githubusercontent.com/3929177/34068937-ff60b5f6-e245-11e7-8d40-8b979b91abeb.png)

**Actual behaviour** 

We have just the name of the types of paper

### other
_The readme files I did, was with the wordpress.org format on my mind. I think, the == Frequently Asked Questions == should stay, not in the .md file but in the .txt file. if the information is not direct inside of the settings page_

### System Information

- Pressbooks mPDF: [3] 
- Pressbooks: [4.5] 
- WordPress: [4.9.1]

**Comment by colomet** [comment]
What if I do create that information in that place? are you agree with that?

**Comment by colomet** [comment]
= Page size Dimensions =

Dimensions Of A Series Paper Sizes
Size	Width x Height (mm)	Width x Height (in)
A0	841 x 1189 mm	        33.1 x 46.8 in
A1	594 x 841 mm	        23.4 x 33.1 in
A2	420 x 594 mm	        16.5 x 23.4 in
A3	297 x 420 mm	        11.7 x 16.5 in
A4	210 x 297 mm	        8.3 x 11.7 in
A5	148 x 210 mm	        5.8 x 8.3 in
A6	105 x 148 mm	        4.1 x 5.8 in
A7	74 x 105 mm	        2.9 x 4.1 in
A8	52 x 74 mm	        2.0 x 2.9 in
A9	37 x 52 mm	        1.5 x 2.0 in
A10	26 x 37 mm	        1.0 x 1.5 in

Dimensions Of B Series Paper Sizes
Size	Width x Height (mm)	Width x Height (in)
B0	1000 x 1414 mm	        39.4 x 55.7 in
B1	707 x 1000 mm	        27.8 x 39.4 in
B2	500 x 707 mm	        19.7 x 27.8 in
B3	353 x 500 mm	        13.9 x 19.7 in
B4	250 x 353 mm	        9.8 x 13.9 in
B5	176 x 250 mm	        6.9 x 9.8 in
B6	125 x 176 mm	        4.9 x 6.9 in
B7	88 x 125 mm	        3.5 x 4.9 in
B8	62 x 88 mm	        2.4 x 3.5 in
B9	44 x 62 mm	        1.7 x 2.4 in
B10	31 x 44 mm	        1.2 x 1.7 in

Dimensions Of C Series Envelope Sizes
Size	Width x Height (mm)	Width x Height (in)
C0	917 x 1297 mm	        36.1 x 51.5 in
C1	648 x 917 mm	        25.5 x 36.1 in
C2	458 x 648 mm	        18.0 x 25.5 in
C3	324 x 458 mm	        12.8 x 18.0 in
C4	229 x 324 mm	        9.0 x 12.8 in
C5	162 x 229 mm	        6.4 x 9.0 in
C6	114 x 162 mm	        4.5 x 6.4 in
C7	81 x 114 mm	        3.2 x 4.5 in
C8	57 x 81 mm	        2.2 x 3.2 in
C9	40 x 57 mm	        1.6 x 2.2 in
C10	28 x 40 mm	        1.1 x 1.6 in

4A0 & 2A0 - The DIN 476 Oversize Formats
Size	Width x Height (mm)	Width x Height (in)
4A0	1682 x 2378 mm	        66.2 x 93.6 in
2A0	1189 x 1682 mm	        46.8 x 66.2 in

Dimensions Of RA & SRA Series Untrimmed Paper Sizes
Size	Width x Height (mm)	Width x Height (in)
RA0	860 x 1220 mm	        33.9 x 48.0 in
RA1	610 x 860 mm	        24.0 x 33.9 in
RA2	430 x 610 mm	        16.9 x 24.0 in
RA3	305 x 430 mm	        12.0 x 16.9 in
RA4	215 x 305 mm	        8.5 x 12.0 in
SRA0	900 x 1280 mm	        35.4 x 50.4 in
SRA1	640 x 900 mm	        25.2 x 35.4 in
SRA2	450 x 640 mm	        17.7 x 25.2 in
SRA3	320 x 450 mm	        12.6 x 17.7 in
SRA4	225 x 320 mm	        8.9 x 12.6 in

US Paper Sizes
Size	Width x Height (mm)	Width x Height (in)
Letter*	216 x 279 mm	        8.5 x 11.0 in
Legal	216 x 356 mm	        8.5 x 14.0 in
Executive 184.2 x 266.7mm       7.0 x 10.0 in
Folio   210 x 330               8.0 x 13.0 in
 
British Imperial Paper Sizes
Size	Width x Height (mm)	Width x Height (in)
Demy 	450.9 x 571.5 mm        17.75 x 22.5 in 	
Royal 	508.0 x 635.0 mm.       20.0 x 25.0 in 	        
Type A paperback 111x178mm
Type B paperback 128x198mm

http://www.papersizes.org/

**Comment by bdolor** [comment]
thanks @colomet — will plug away at this.

**Comment by bdolor** [comment]
resolved in https://github.com/BCcampus/pressbooks-mpdf/commit/fbe68e9e08d7f874a1ac8930e2ebab83b79b98a8 and https://github.com/BCcampus/pressbooks-mpdf/commit/438d2d008b4d05d458be7e9ff4aab327b112225e
