### ISSUE TITLE
Can't meet PHP ^7.1 dep requirements

### ISSUE THREAD

**Issue by monkecheese** [BCcampus/pressbooks-mpdf#46]
### Description 

Given our hosting solution, we are unable to upgrade beyond PHP 7.0, making the PHP ^7.1 requirement for installing dependencies impossible for us.

**Expected behaviour** 

`composer install` should install all of the dependencies

**Actual behaviour** 

We get an error in the console as follows:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/yaml v4.0.1 -> satisfiable by symfony/yaml[v4.0.1].
    - symfony/yaml v4.0.1 requires php ^7.1.3 -> your PHP version (7.0.19) does not satisfy that requirement.
  Problem 3
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.19) does not satisfy that requirement.
    - phpunit/phpunit-mock-objects 3.4.4 requires doctrine/instantiator ^1.0.2 -> satisfiable by doctrine/instantiator[1.1.0].
    - Installation request for phpunit/phpunit-mock-objects 3.4.4 -> satisfiable by phpunit/phpunit-mock-objects[3.4.4].
```

### Steps to reproduce the problem

Install PHP version 7.0.x and attempt to install dependencies for the plugin via `composer install`

### System Information

- Pressbooks mPDF: 3.0.0
- Pressbooks: 4.5.0 
- WordPress: 4.9.1

**Comment by greatislander** [comment]
`composer install --no-dev` should work as those dependencies are only for unit testing.

**Comment by monkecheese** [comment]
Ah yes, thank you @greatislander.  Oversight on my part.  :)
