### ISSUE TITLE
issue on the exportation

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#47]
### Description 

If i export a PDF i get a warming

![captura de pantalla 2018-01-02 a las 12 36 15](https://user-images.githubusercontent.com/3929177/34485413-d2782640-efca-11e7-93c5-eab3a111fbec.png)

**Expected behaviour** 

Just to export

**Actual behaviour** 

Export the book, and looks lik it works the pdf, but I have the warming in the exporting page

### Steps to reproduce the problem

Just export the book

### System Information

- Pressbooks mPDF: [3.0] 
- Pressbooks: [4.5] 
- WordPress: [4.9.1]

**Comment by bdolor** [comment]
@colomet are you still getting this error? I haven't seen it before and would like to be able to reproduce.

**Comment by colomet** [comment]
I do try, and I can not see it again. Maybe a PB update fix it. If it happen again, i will text
