### ISSUE TITLE
Not exporting all chapters in Table of Contents

### ISSUE THREAD

**Issue by beckej13820** [BCcampus/pressbooks-mpdf#51]
### Description 

When exporting PDFs, Table of contents is coming in incomplete. Some but not all chapters are not being displayed.

![screen shot 2018-02-26 at 7 44 03 pm](https://user-images.githubusercontent.com/29982981/36730254-c44217de-1b94-11e8-94b8-561811ad5c42.png)

**Expected behaviour** 

I would expect all the chapter titles in the table of contents.
![screen shot 2018-02-26 at 7 45 12 pm](https://user-images.githubusercontent.com/29982981/36730269-d435a4e4-1b94-11e8-9cc8-4729742358e9.png)

**Actual behaviour** 

I can't make out a pattern in the behavior. Some books have no chapter titles at all, some books have some but not all.

![screen shot 2018-02-27 at 8 09 57 am](https://user-images.githubusercontent.com/29982981/36730541-ce8d3f92-1b95-11e8-93bc-8e6a0f50f860.png)

### Steps to reproduce the problem

I network disabled all plugins except Pressbooks, Pressbooks Aldine, Pressbooks McLuhan, Pressbooks-MPDF 

Export a book to PDF and PDF only. 

### System Information

- mPDF for Pressbooks: 3.1.0-rc.1
- Pressbooks: 5.0.0-rc.1
- WordPress: 4.9.4

**Comment by bdolor** [comment]
thank you @beckej13820 - I will look into this.

**Comment by colomet** [comment]
also the TOC of the pdf is not complete, do not have the names

![captura de pantalla 2018-03-02 a las 22 19 44](https://user-images.githubusercontent.com/3929177/36922446-21595ede-1e68-11e8-810f-cb89a3ee8608.png)

**Comment by colomet** [comment]
13 is the part, and the name is correct, but 14, 15 and 16 have just the chapter number, not the name.

Also, maybe the chapters and parts must follow different numeration. We can not have 100 chapters and 10 parts and the page number 110. looks complicate maybe. 

also Pressbooks do not count the parts for the numbered of the chapters.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/pressbooks-mpdf/pull/54
