### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#56]
### Description 

To create a form of ex libris, passive watermark, for free output. 

To have an option that by activate, each new site or old site that have activate mPDF will have a watermar.
To have an option for each book that can be independent activated or not as superadmin for each book (that would be the first step, so in the future, we can create if we wish an automatic way to have or not watermarks after the payment)

**Expected behaviour** 

To have or not watermarks upon request

**Actual behaviour** 

we have not watermarks

### System Information

- mPDF for Pressbooks: [3.1.1] 
- Pressbooks: [5.2] 
- WordPress: [4.9.4]

**Comment by bdolor** [comment]
I can't say that this is something, under our current funding model, that we would be able to support.  The idea behind creating and maintaining mPDF plugin was to remove a financial barrier imposed by the licensing requirement of PrinceXML for publishing PDF documents in Pressbooks. This feature request would put those barriers back up (requiring payment to remove a watermark).
