### ISSUE TITLE
Images and captions would not centre on PDF export

### ISSUE THREAD

**Issue by Gotomary** [BCcampus/pressbooks-mpdf#57]
### Description 

The images and its captions are not centred when exporting to PDF.

**Expected behaviour** 

I expected the images and their captions be centred.

**Actual behaviour** 

Images and captions are on the left-hand side of the page.

### Steps to reproduce the problem

Export to PDF using mPDF on Pressbooks. mPDF Theme options are set to A5, left margin 15 and right margin 30.

### System Information

- mPDF for Pressbooks: Version 3.1.1 
- Pressbooks: Version 5.1.0

**Comment by bdolor** [comment]
resolved in https://github.com/BCcampus/pressbooks-mpdf/commit/06afab1579d6b96dff52a8c9882172ac5619c8e9
