### ISSUE TITLE
Hanging Indents display left and justified ?

### ISSUE THREAD

**Issue by sswettenham** [BCcampus/pressbooks-mpdf#6]
WP 4.4.1, PB 3.1.2, PBT 2.1.2, PmPDF 1.0.1
This has been a long standing issue that I would like to figure out how to fix.
Code:
![edit back matter professional writing in the health disciplines pressbooks 2016-02-02 13-27-45](https://cloud.githubusercontent.com/assets/360534/12749518/7332da9a-c9b1-11e5-898c-63d897e71370.png)
PDF:
![hangingindent](https://cloud.githubusercontent.com/assets/360534/12749552/b6398e88-c9b1-11e5-86c0-c70885897200.png)

**Comment by bdolor** [comment]
The problem, as it is defined and as far as I can tell, is that you've styled something with `p.hanging-indent` and in the output, it is displaying as a hanging indent? In the off chance that I've missed something obvious and this indeed requires further attention, please help me better understand how it is that: 

a.) this is a problem.
b.) this is a problem that can/should be resolved by a developer.

**Comment by sswettenham** [comment]
In creating an APA reference the hanging-indent was used with the intent of left-aligned text.  However, some of the text gets spread-out (red boxes in above message image) and other text does not, maybe suggesting justified format?

a.) how can all the text in a hanging-indent not be spread out so that all the text is consistent?
     Is this a CSS setting in mPDF or somewhere else?

b.) if justified is the default setting for hanging-indent in the Pressbooks Textbook theme, then I would like to know where I can go change that?

Thanks,
Regards,
Steve
