### ISSUE TITLE
mPDF export fails on Pressbooks dev

### ISSUE THREAD

**Issue by josiegray** [BCcampus/pressbooks-mpdf#61]
### Description 

When I try to export a book as a mPDF on pressbooksdev, the export fails and I get the following message: 

This page isn’t working
pressbooksdev.bccampus.ca is currently unable to handle this request.
HTTP ERROR 500

**Expected behaviour** 

When I select mPDF as an export option and try to export a book, Pressbooks creates an mPDF file for download. 

**Actual behaviour** 

When I try to export a book as an mPDF, I am shown a page with the following error message and no mPDF file is created: 

This page isn’t working
pressbooksdev.bccampus.ca is currently unable to handle this request.
HTTP ERROR 500

### Steps to reproduce the problem

1. Select mPDF as an export option for a book in pressbooks dev.
2. Try to export the book as an mPDF. 
3. You are redirected to the error message. 

### System Information
pressbooksdev

- mPDF for Pressbooks: [Enter PBmPDF Version here]

**Comment by josiegray** [comment]
This happened on this book: https://pressbooksdev.bccampus.ca/testing/ and this book: https://pressbooksdev.bccampus.ca/knowinghome/

**Comment by bdolor** [comment]
thank you for the bug report @josiegray - this ended up being a problem with our build process which was isolated to our development environment. It has been resolved, and is working now. Thanks again.
