### ISSUE TITLE
Feature request: To no export parts setting option

### ISSUE THREAD

**Issue by colomet** [BCcampus/pressbooks-mpdf#62]
### Description 

Some times, we have so many parts. All of them are for organization behaviour. We do not use in web view.  So, maybe is good idea to have an option and to not export as pdf.

**Expected behaviour** 

To export a book. To not export the parts of the book.

**Actual behaviour** 

We export parts and chapters

### Steps to reproduce the problem

export a book as pdf and take a look.

### System Information

- mPDF for Pressbooks: [3.1.3] 
- Pressbooks: [5.4] 
- WordPress: [4.9.7]

**Comment by greatislander** [comment]
@colomet Setting parts to 'Invisible' should prevent it from being shown in TOC/exports:

<img width="294" alt="screen shot 2018-07-12 at 3 07 03 pm" src="https://user-images.githubusercontent.com/605361/42656559-43775766-85e5-11e8-8254-224814149fe6.png">

**Comment by bdolor** [comment]
thanks @greatislander
@colomet I've confirmed this feature works with mPDF for pressbooks
