### ISSUE TITLE
Table of Contents missing when Part title is changed

### ISSUE THREAD

**Issue by ghost** [BCcampus/pressbooks-mpdf#7]
Assuming "Set as ebook start-point" has been enabled for first item in Front Matter...

Modifying Main Body title to something else such as "Part I" will disable Table of Contents generation.

(Reproduced on fresh install instance of Pressbooks)

**Comment by rwestmacott** [comment]
After thorough testing and a code review, I was unable to duplicate this issue. If any subsequent reports are logged, we can continue to investigate.
