### ISSUE TITLE
EventStream Connection Error when trying to export

### ISSUE THREAD

**Issue by pjohanneson** [BCcampus/pressbooks-mpdf#76]
### Description 

Can't export to PDF -- I get `EventStream Connection Error` when attempting to export a book.

**Expected behaviour** 

I want to be able to export my book to PDF. Other exports are successful.

**Actual behaviour** 

When attempting to export to PDF, I get the error message `EventStream Connection Error`.

### Steps to reproduce the problem

* Installed pressbooks-mPDF.
* Followed the [installation instructions here](https://docs.pressbooks.org/installation/).
* Ensured that the server ID `www-data` could write to the directories:
    *  wp-content/plugins/pressbooks-mpdf/symbionts/mpdf/ttfontdata
    * wp-content/plugins/pressbooks-mpdf/symbionts/mpdf/tmp
    * wp-content/plugins/pressbooks-mpdf/symbionts/mpdf/graph_cache
* Installed or updated the PHP libraries `gd`, `mbstring`, `bcmath`, and `xml`.
* Restarted Apache.
* Went to `[server]/[site]/wp-admin/options.php?page=pb_export` and attempted to export to **PDF (mPDF)**.

### System Information

- mPDF for Pressbooks: 3.2.4
- Pressbooks: 5.7.0
- WordPress: 5.1.1

**Comment by bdolor** [comment]
@pjohanneson I suspect the error is being thrown here: https://github.com/pressbooks/pressbooks/blob/c28981f5cf6c35e7fb8b90dda88e633d1efff423/assets/src/scripts/export.js#L80 

I've tried recreating this locally but cannot. Export functionality works as expected. 

BTW I will be releasing a patch version of mPDF shortly, but I'm not sure it will address the issue you're experiencing. 

Has mPDF worked for you before or is this a new install?

**Comment by pjohanneson** [comment]
This is a new install of mPDF, though I've had PressBooks installed for a while. I may spin up a VM and see if I can make the error happen again.

**Comment by bdolor** [comment]
If it's a content related problem and your book is openly licensed/shareable you could point to it and we could troubleshoot from there.

**Comment by pjohanneson** [comment]
Fixed. I was using a Github-sourced version of the plugin, and I hadn't run `composer install`, so I was missing dependencies. Mea culpa.
